config/routes.rb
Rails.application.routes.draw do
  concern :discard do
    member do
      get 'discard'
      patch 'discard'
      patch 'restore'
      get 'delete', constraints: { format: 'js' }
    end
  end
  concern :autocomplete do
    collection do
      get 'autocomplete'
    end
  end
  concern :clone do
    member do
      get 'clone'
    end
  end
  resources :shooting_velocities do
    concerns [:autocomplete, :discard]
  end
  resources :guns do
    concerns [:discard]
  end
  resources :shooting_groups do
    collection do
      get 'next_number', constraints: { format: 'json' }
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :shooting_logs do
    concerns [:autocomplete, :discard]
  end
  resources :shooting_locations do
    concerns [:discard]
  end
  resources :loads do
    member do
      get 'calculate_velocity'
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :brasses do
    concerns [:discard]
  end
  resources :calibers do
    concerns [:discard]
  end
  resources :primers do
    concerns [:discard]
  end
  resources :powders do
    concerns [:discard]
  end
  resources :bullets do
    concerns [:discard]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  get '/ballistic_calculator', to: 'ballistic_calculator#new', as: :ballistic_calculator
  post '/ballistic_calculator', to: 'ballistic_calculator#create', as: nil
  get 'users/settings', to: 'user_settings#show', as: :user_settings
  get 'users/settings/edit', to: 'user_settings#edit', as: :user_settings_edit
  put 'users/settings', to: 'user_settings#update', as: nil
  get "/*id" => 'pages#show', as: :page, format: false
  root to: "pages#show", id: 'home'
end

app/models/shooting_log.rb
# frozen_string_literal: true

class ShootingLog < ApplicationRecord
  include UserOwned
  include HasWindSpeed
  belongs_to :shooting_location, optional: true
  belongs_to :caliber, optional: true
  has_many :shooting_groups, dependent: :destroy

  validates :date, presence: true
  validates :time, presence: true

  scoped_search on: [:date], complete_value: true
  scoped_search relation: :shooting_location, on: :name, complete_value: true, rename: :location
  scoped_search relation: :caliber, on: :name, complete_value: true, rename: :caliber

  def name_full
    date
  end

  def temperature_full
    return temperature unless temperature.present?
    "#{temperature} #{temperature_unit}"
  end

  def pressure_full
    return pressure unless pressure.present?
    "#{pressure} #{pressure_unit}"
  end

  def temperature_unit
    self[:temperature_unit].present? ? self[:temperature_unit] : user.settings(:default_units).temperature
  end

  def pressure_unit
    self[:pressure_unit].present? ? self[:pressure_unit] : user.settings(:default_units).pressure
  end
end

app/controllers/shooting_logs_controller.rb
# frozen_string_literal: true

class ShootingLogsController < ApplicationController
  include DiscardController

  before_action :set_index, only: [:index]
  before_action :set_shooting_log, only: [:show, :edit, :update, :discard, :restore, :delete, :destroy]
  before_action :set_associations, only: [:new, :create, :edit, :update]

  # GET /shooting_logs
  # GET /shooting_logs.json
  def index
  end

  # GET /shooting_logs/1
  # GET /shooting_logs/1.json
  def show
    authorize @shooting_log
  end

  # GET /shooting_logs/new
  def new
    @shooting_log = ShootingLog.new
    @shooting_log.user = current_user
    authorize @shooting_log
  end

  # GET /shooting_logs/1/edit
  def edit
    authorize @shooting_log
  end

  # POST /shooting_logs
  # POST /shooting_logs.json
  def create
    @shooting_log = ShootingLog.new(shooting_log_params)
    @shooting_log.user = current_user
    authorize @shooting_log

    respond_to do |format|
      if @shooting_log.save
        format.html { redirect_to @shooting_log, notice: "Shooting log was successfully created." }
        format.json { render :show, status: :created, location: @shooting_log }
      else
        format.html { render :new }
        format.json { render json: @shooting_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shooting_logs/1
  # PATCH/PUT /shooting_logs/1.json
  def update
    authorize @shooting_log
    respond_to do |format|
      if @shooting_log.update(shooting_log_params)
        format.html { redirect_to @shooting_log, notice: "Shooting log was successfully updated." }
        format.json { render :show, status: :ok, location: @shooting_log }
      else
        format.html { render :edit }
        format.json { render json: @shooting_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shooting_logs/1
  # DELETE /shooting_logs/1.json
  def destroy
    authorize @shooting_log
    @shooting_log.destroy
    respond_to do |format|
      format.html { redirect_to shooting_logs_url, notice: "Shooting log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_associations
      @shooting_locations = policy_scope(ShootingLocation).kept
      @calibers = policy_scope(Caliber).kept
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_shooting_log
      @shooting_log = policy_scope(ShootingLog).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shooting_log_params
      params.require(:shooting_log).permit(:date, :time, :shooting_location_id, :caliber_id, :temperature, :temperature_unit,
                                           :pressure, :pressure_unit, :angle, :conditions, :humidity,
                                           :wind_speed, :wind_speed_unit, :wind_direction, :notes)
    end

    def sortable_columns
      ["date"]
    end

    def default_sort_column
      "date"
    end

    def default_sort_direction
      "desc"
    end
end

app/helpers/shooting_logs_helper.rb
# frozen_string_literal: true

module ShootingLogsHelper
end

app/views/shooting_logs/_form.html.erb
<%= simple_form_for(@shooting_log) do |f| %>
  <%= render 'form_errors', f: f %>

  <div class="form-inputs">
    <%= f.input :date, as: :date_picker, input_html: { class: 'col-sm-4' } %>
    <%= f.input :time, as: :time_picker, input_html: { class: 'col-sm-4' } %>
    <%= f.association :shooting_location, collection: @shooting_locations %>
    <%= f.association :caliber, collection: @calibers %>
    <%= f.input :temperature do %>
      <%= f.input_field :temperature, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :temperature_unit, as: :select, collection: Unit.temperature, class: 'col-sm-2' %>
    <% end %>
    <%= f.input :pressure do %>
      <%= f.input_field :pressure, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :pressure_unit, as: :select, collection: Unit.pressure, class: 'col-sm-2' %>
    <% end %>
    <%= f.input :humidity, hint: 'percent (%)' %>
    <%= f.input :wind_speed do %>
      <%= f.input_field :wind_speed, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :wind_speed_unit, as: :select, collection: Unit.velocity, class: 'col-sm-2' %>
      <%= f.input_field :wind_direction, class: 'col-sm-4', placeholder: 'Direction in degrees' %>
    <% end %>
    <%= f.input :angle %>
    <%= f.input :conditions %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/shooting_logs/edit.html.erb
<%= edit_header(@shooting_log) %>
<%= render 'form', shooting_log: @shooting_log %>

app/views/shooting_logs/index.html.erb
<%= index_header(ShootingLog) %>

<%= search_bar(ShootingLog) %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= sort_link 'date' %></th>
      <th>Shooting location</th>
      <th>Shooting Groups</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shooting_logs.each do |shooting_log| %>
      <tr>
        <td><%= link_to shooting_log.date, shooting_log %></td>
        <td><%= shooting_log.shooting_location.name %></td>
        <% if shooting_log.shooting_groups.present? %>
        <td><%= link_to "#{shooting_log.shooting_groups.count} shooting groups", shooting_groups_path(search: "date = #{shooting_log.date}") %></td>
        <% else %>
        <td></td>
        <% end %>
        <td><%= index_actions(shooting_log) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pagination(ShootingLog) %>

app/views/shooting_logs/new.html.erb
<%= new_header(@shooting_log) %>
<%= render 'form', shooting_log: @shooting_log %>

app/views/shooting_logs/show.html.erb
<%= show_header(@shooting_log) do %>
<% new_group_params = {shooting_log_id: @shooting_log.id, caliber_id: @shooting_log.caliber.present? ? @shooting_log.caliber.id : nil }%>
<%= link_to(new_shooting_group_path(new_group_params), class: 'dropdown-item') do %>
  <span class="fa fa-plus"></span>New Group
<% end %>
<% new_velocity_params = {date: @shooting_log.date, caliber_id: @shooting_log.caliber.present? ? @shooting_log.caliber.id : nil } %>
<%= link_to(new_shooting_velocity_path(new_velocity_params), class: 'dropdown-item') do %>
  <span class="fa fa-plus"></span>New Velocities
<% end %>
<% end %>

<dl class='dl-horizontal'>
  <dt>Date:</dt>
  <dd><%= @shooting_log.date %></dd>

  <dt>Time:</dt>
  <dd><%= print_time(@shooting_log.time) %></dd>

  <dt>Shooting location:</dt>
  <dd><%= @shooting_log.shooting_location.name %></dd>

  <dt>Caliber:</dt>
  <dd><%= @shooting_log.caliber.present? ? @shooting_log.caliber.name : '' %></dd>

  <dt>Temperature:</dt>
  <dd><%= @shooting_log.temperature_full %></dd>

  <dt>Pressure:</dt>
  <dd><%= @shooting_log.pressure_full %></dd>

  <dt>Humidity:</dt>
  <dd><%= @shooting_log.humidity %></dd>

  <dt>Wind speed:</dt>
  <dd><%= @shooting_log.wind_speed_full %></dd>

  <dt>Angle:</dt>
  <dd><%= @shooting_log.angle %></dd>

  <dt>Conditions:</dt>
  <dd><%= @shooting_log.conditions %></dd>

  <dt>Notes:</dt>
  <dd><%= @shooting_log.notes %></dd>
</dl>

<h3>Groups</h3>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Load</th>
      <th>Group size</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shooting_log.shooting_groups.each do |shooting_group| %>
      <tr>
        <td><%= link_to shooting_group.name, shooting_group %></td>
        <td><%= shooting_group.load.name %></td>
        <td><%= shooting_group.group_size %></td>
        <td><%= index_actions(shooting_group) %></td>
      </tr>
    <% end %>
  </tbody>
</table>