config/routes.rb
Rails.application.routes.draw do
  concern :discard do
    member do
      get 'discard'
      patch 'discard'
      patch 'restore'
      get 'delete', constraints: { format: 'js' }
    end
  end
  concern :autocomplete do
    collection do
      get 'autocomplete'
    end
  end
  concern :clone do
    member do
      get 'clone'
    end
  end
  resources :shooting_velocities do
    concerns [:autocomplete, :discard]
  end
  resources :guns do
    concerns [:discard]
  end
  resources :shooting_groups do
    collection do
      get 'next_number', constraints: { format: 'json' }
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :shooting_logs do
    concerns [:autocomplete, :discard]
  end
  resources :shooting_locations do
    concerns [:discard]
  end
  resources :loads do
    member do
      get 'calculate_velocity'
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :brasses do
    concerns [:discard]
  end
  resources :calibers do
    concerns [:discard]
  end
  resources :primers do
    concerns [:discard]
  end
  resources :powders do
    concerns [:discard]
  end
  resources :bullets do
    concerns [:discard]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  get '/ballistic_calculator', to: 'ballistic_calculator#new', as: :ballistic_calculator
  post '/ballistic_calculator', to: 'ballistic_calculator#create', as: nil
  get 'users/settings', to: 'user_settings#show', as: :user_settings
  get 'users/settings/edit', to: 'user_settings#edit', as: :user_settings_edit
  put 'users/settings', to: 'user_settings#update', as: nil
  get "/*id" => 'pages#show', as: :page, format: false
  root to: "pages#show", id: 'home'
end

app/models/load.rb
# frozen_string_literal: true

class Load < ApplicationRecord
  include UserOwned
  include HasCaliber
  include HasVelocity
  belongs_to :brass
  belongs_to :bullet
  belongs_to :powder
  belongs_to :primer
  has_many :shooting_groups, dependent: :destroy
  has_many :shooting_velocities, dependent: :destroy

  validates :date, presence: true
  validates :powder_weight, numericality: true, presence: true
  validates :col, numericality: true, presence: true
  validates :brass_length, numericality: true, allow_blank: true
  validates :brass_uses, numericality: { only_integer: true }, allow_blank: true
  validates :run_out, numericality: true, allow_blank: true
  validates :rounds, numericality: { only_integer: true }, allow_blank: true

  scoped_search on: [:date], complete_value: true
  scoped_search on: [:brass_length, :col, :powder_weight], complete_value: true
  scoped_search relation: :powder, on: :name, complete_value: true, rename: :powder
  scoped_search relation: :primer, on: :name, complete_value: true, rename: :primer
  scoped_search relation: :brass, on: :name, complete_value: true, rename: :brass
  scoped_search relation: :bullet, on: :name, complete_value: true, rename: :bullet
  scoped_search relation: :bullet, on: :grain, complete_value: true, rename: :bullet_grain

  scope :kept, -> { undiscarded.joins(:user, :caliber, :brass, :bullet, :powder, :primer)
                      .merge(User.kept).merge(Caliber.kept).merge(Brass.kept)
                      .merge(Bullet.kept).merge(Powder.kept).merge(Primer.kept) }

  def name
    "#{date} - #{bullet.name_caliber_grain} - #{powder.name} (#{powder_weight}gr)"
  end

  def name_full
    name
  end

  def brass_length_full
    return brass_length unless brass_length.present?
    "#{brass_length} #{brass_length_unit}"
  end

  def col_full
    return col unless col.present?
    "#{col} #{col_unit}"
  end

  def run_out_full
    return run_out unless run_out.present?
    "#{run_out} #{run_out_unit}"
  end

  def brass_length_unit
    self[:brass_length_unit].present? ? self[:brass_length_unit] : user.settings(:default_units).length
  end

  def col_unit
    self[:col_unit].present? ? self[:col_unit] : user.settings(:default_units).length
  end

  def run_out_unit
    self[:run_out_unit].present? ? self[:run_out_unit] : user.settings(:default_units).length
  end

  def calculate_velocity
    velocities = shooting_velocities.map(&:velocities).flatten
    return nil unless velocities.present?
    avg = velocities.mean
    avg.to_i
  end

  def clone_record
    new_load = self.dup
    new_load.date = nil
    new_load.velocity = nil
    new_load
  end
end

app/controllers/loads_controller.rb
# frozen_string_literal: true

class LoadsController < ApplicationController
  include DiscardController

  before_action :set_index, only: [:index]
  before_action :set_load, only: [:show, :edit, :update, :discard, :restore, :delete, :destroy, :calculate_velocity, :clone]
  before_action :set_associations, only: [:new, :create, :edit, :update, :clone]

  # GET /loads
  # GET /loads.json
  def index
  end

  # GET /loads/1
  # GET /loads/1.json
  def show
    authorize @load
  end

  # GET /loads/new
  def new
    @load = Load.new
    @load.user = current_user
    authorize @load
  end

  # GET /loads/1/edit
  def edit
    authorize @load
  end

  # POST /loads
  # POST /loads.json
  def create
    @load = Load.new(load_params)
    @load.user = current_user
    authorize @load

    respond_to do |format|
      if @load.save
        format.html { redirect_to @load, notice: "Load was successfully created." }
        format.json { render :show, status: :created, location: @load }
      else
        format.html { render :new }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loads/1
  # PATCH/PUT /loads/1.json
  def update
    authorize @load
    respond_to do |format|
      if @load.update(load_params)
        format.html { redirect_to @load, notice: "Load was successfully updated." }
        format.json { render :show, status: :ok, location: @load }
      else
        format.html { render :edit }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loads/1
  # DELETE /loads/1.json
  def destroy
    authorize @load
    @load.destroy
    respond_to do |format|
      format.html { redirect_to loads_url, notice: "Load was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /loads/1/calculate_velocity.json
  def calculate_velocity
    authorize @load
    respond_to do |format|
      format.html do
        if @load.update(velocity: @load.calculate_velocity)
          redirect_to @load, notice: "Load velocity successfully updated."
        else
          render :show
        end
      end
      format.json { render json: { velocity: @load.calculate_velocity } }
    end
  end

  # GET /loads/1/clone
  def clone
    @load = @load.clone_record
    authorize @load
    render :new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_load
      @load = policy_scope(Load).find(params[:id])
    end

    def set_associations
      @calibers = policy_scope(Caliber).kept
      @brass = policy_scope(Brass).kept
      @bullets = policy_scope(Bullet).kept
      @powders = policy_scope(Powder).kept
      @primers = policy_scope(Primer).kept
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def load_params
      params.require(:load).permit(:caliber_id, :brass_id, :brass_length, :date, :bullet_id, :powder_id, :powder_weight,
                                   :primer_id, :col, :velocity, :run_out, :brass_uses, :rounds, :notes,
                                   :brass_length_unit, :col_unit, :run_out_unit, :velocity_unit)
    end

    def sortable_columns
      ["date"]
    end

    def default_sort_column
      "date"
    end

    def default_sort_direction
      "desc"
    end
end

app/helpers/loads_helper.rb
# frozen_string_literal: true

module LoadsHelper
end

app/views/loads/_form.html.erb
<%= simple_form_for(@load) do |f| %>
  <%= render 'form_errors', f: f %>

  <div class="form-inputs">
    <%= f.input :date, as: :date_picker, input_html: { class: 'col-sm-4' } %>
    <%= f.association :caliber, collection: @calibers %>
    <%= f.input :brass_id, collection: @calibers,
                label_method: :name_caliber, as: :grouped_select, group_method: :brasses, required: true,
                input_html: { class: "#{is_invalid(@load, :bullet)}" } %>
    <%= f.input :brass_length do %>
      <%= f.input_field :brass_length, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :brass_length_unit, as: :select, collection: Unit.length, class: 'col-sm-2' %>
    <% end %>
    <%= f.input :brass_uses %>
    <%= f.input :bullet_id, collection: @calibers,
                label_method: :name_caliber_grain, as: :grouped_select, group_method: :bullets, required: true,
                input_html: { class: "#{is_invalid(@load, :bullet)}" } %>
    <%= f.input :powder do %>
      <%= f.input_field :powder_id, as: :select, collection: @powders, required: true,
                        class: "col-sm-4 form-control input_field #{is_invalid(@load, :powder)}" %>
      <%= f.label 'Weight:', required: true, class: 'col-sm-3 col-lg-2 text-sm-right' %>
      <%= f.input_field :powder_weight, required: true, class: 'form-control input_field col-sm-2' %>
    <% end %>
    <%= f.association :primer, collection: @primers %>
    <%= f.input :col, required: true, label: 'COL' do %>
      <%= f.input_field :col, required: true, class: 'form-control input_field col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :col_unit, as: :select, collection: Unit.length, class: 'col-sm-2' %>
    <% end %>
    <%= f.input :run_out do %>
      <%= f.input_field :run_out, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :run_out_unit, as: :select, collection: Unit.length, class: 'col-sm-2' %>
    <% end %>
    <%= f.input :velocity do %>
      <%= f.input_field :velocity, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :velocity_unit, as: :select, collection: Unit.velocity, class: 'col-sm-2' %>
      <% if ! @load.new_record? %>
        <%= link_to '#', id: 'calculate-velocity', class: 'btn btn-outline-secondary ml-sm-2 mt-sm-0 mt-2', data: { id: @load.id, toggle: 'tooltip', placement: 'bottom' }, title: 'Calculate based on defined velocities' do %>
          <%= content_tag :span, nil, class: 'fa fa-calculator' %>Calculate velocity
        <% end %>
      <% end %>
    <% end %>
    <%= f.input :rounds, label: 'Number of Rounds' %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/loads/edit.html.erb
<%= edit_header(@load) %>
<%= render 'form', load: @load %>

app/views/loads/index.html.erb
<%= index_header(Load) %>

<%= search_bar(Load) %>

<table class='table table-striped table-condensed table-bordered'>
  <thead>
    <tr>
      <th>ID</th>
      <th><%= sort_link 'date' %></th>
      <th>Bullet</th>
      <th>Powder</th>
      <th>Primer</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @loads.each do |load| %>
      <tr>
        <td><%= link_to load.id, load %></td>
        <td><%= link_to load.date, load %></td>
        <td><%= load.bullet.name_caliber_grain %></td>
        <td><%= load.powder.name %> - <%= load.powder_weight %> gr</td>
        <td><%= load.primer.name %></td>
        <td>
          <%= index_actions(load) do %>
            <%= link_to('Clone', clone_load_path(load), class: 'dropdown-item') %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pagination(Load) %>

app/views/loads/new.html.erb
<%= new_header(@load) %>
<%= render 'form', load: @load %>

app/views/loads/show.html.erb
<%= render 'errors', object: @load %>
<%= show_header(@load) do %>
<%= link_to(calculate_velocity_load_path(@load), class: 'dropdown-item') do %>
  <span class="fa fa-calculator"></span>Calculate velocity
<% end %>
<% new_velocity_params = {load_id: @load.id, caliber_id: @load.caliber.id} %>
<%= link_to(new_shooting_velocity_path(new_velocity_params), class: 'dropdown-item') do %>
  <span class="fa fa-plus"></span>New Velocities
<% end %>
<% new_group_params = {load_id: @load.id, caliber_id: @load.caliber.id}%>
<%= link_to(new_shooting_group_path(new_group_params), class: 'dropdown-item') do %>
  <span class="fa fa-plus"></span>New Group
<% end %>
<% end %>

<dl class='dl-horizontal'>
  <dt>ID:</dt>
  <dd><%= @load.id %></dd>

  <dt>Date:</dt>
  <dd><%= @load.date %></dd>

  <dt>Brass:</dt>
  <dd><%= @load.brass.name_caliber %></dd>

  <dt>Brass length:</dt>
  <dd><%= @load.brass_length_full %></dd>

  <dt>Brass uses:</dt>
  <dd><%= @load.brass_uses %></dd>

  <dt>Bullet:</dt>
  <dd><%= @load.bullet.name_caliber_grain %></dd>

  <dt>Powder:</dt>
  <dd><%= @load.powder.name %></dd>

  <dt>Powder weight:</dt>
  <dd><%= @load.powder_weight %></dd>

  <dt>Primer:</dt>
  <dd><%= @load.primer.name %></dd>

  <dt>COL:</dt>
  <dd><%= @load.col_full %></dd>

  <dt>Run Out:</dt>
  <dd><%= @load.run_out_full %></dd>

  <dt>Velocity:</dt>
  <dd><%= @load.velocity_full %></dd>

  <dt>Number of Rounds:</dt>
  <dd><%= @load.rounds %></dd>

  <dt>Notes:</dt>
  <dd><%= simple_format @load.notes %></dd>
</dl>

<h3>Groups</h3>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Group size</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @load.shooting_groups.each do |shooting_group| %>
      <tr>
        <td><%= link_to shooting_group.name, shooting_group %></td>
        <td><%= shooting_group.group_size %></td>
        <td><%= index_actions(shooting_group) %></td>
      </tr>
    <% end %>
  </tbody>
</table>