config/routes.rb
Rails.application.routes.draw do
  concern :discard do
    member do
      get 'discard'
      patch 'discard'
      patch 'restore'
      get 'delete', constraints: { format: 'js' }
    end
  end
  concern :autocomplete do
    collection do
      get 'autocomplete'
    end
  end
  concern :clone do
    member do
      get 'clone'
    end
  end
  resources :shooting_velocities do
    concerns [:autocomplete, :discard]
  end
  resources :guns do
    concerns [:discard]
  end
  resources :shooting_groups do
    collection do
      get 'next_number', constraints: { format: 'json' }
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :shooting_logs do
    concerns [:autocomplete, :discard]
  end
  resources :shooting_locations do
    concerns [:discard]
  end
  resources :loads do
    member do
      get 'calculate_velocity'
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :brasses do
    concerns [:discard]
  end
  resources :calibers do
    concerns [:discard]
  end
  resources :primers do
    concerns [:discard]
  end
  resources :powders do
    concerns [:discard]
  end
  resources :bullets do
    concerns [:discard]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  get '/ballistic_calculator', to: 'ballistic_calculator#new', as: :ballistic_calculator
  post '/ballistic_calculator', to: 'ballistic_calculator#create', as: nil
  get 'users/settings', to: 'user_settings#show', as: :user_settings
  get 'users/settings/edit', to: 'user_settings#edit', as: :user_settings_edit
  put 'users/settings', to: 'user_settings#update', as: nil
  get "/*id" => 'pages#show', as: :page, format: false
  root to: "pages#show", id: 'home'
end

app/models/shooting_group.rb
# frozen_string_literal: true

class ShootingGroup < ApplicationRecord
  include UserOwned
  include HasCaliber
  include HasLoad
  include HasWindSpeed

  belongs_to :shooting_log
  delegate :bullet, to: :load

  validates :distance, presence: true, numericality: { only_integer: true }
  validates :number, presence: true, numericality: { only_integer: true }, uniqueness: { scope: [:shooting_log, :load, :user, :distance] }
  validates :elevation_adjustment_direction, absence: true, unless: Proc.new { |a| a.elevation_adjustment.present? }
  validates :windage_adjustment_direction, absence: true, unless: Proc.new { |a| a.windage_adjustment.present? }

  scoped_search on: [:distance], complete_value: true
  scoped_search relation: :shooting_log, on: :date, complete_value: true, rename: :date

  scope :kept, -> { undiscarded.joins(:load, :caliber, :shooting_log).merge(Load.kept).merge(Caliber.kept).merge(ShootingLog.kept) }

  def name
    "#{shooting_log.date} - ##{number} (#{distance} #{distance_unit})"
  end

  def name_full
    name
  end

  def distance_unit
    self[:distance_unit].present? ? self[:distance_unit] : user.settings(:default_units).distance
  end

  def elevation_adjustment_unit
    self[:elevation_adjustment_unit].present? ? self[:elevation_adjustment_unit] : user.settings(:default_units).scope_adjustment
  end

  def windage_adjustment_unit
    self[:windage_adjustment_unit].present? ? self[:windage_adjustment_unit] : user.settings(:default_units).scope_adjustment
  end

  def group_size_unit
    self[:group_size_unit].present? ? self[:group_size_unit] : user.settings(:default_units).length
  end

  def distance_full
    return distance unless distance.present?
    "#{distance} #{distance_unit}"
  end

  def elevation_adjustment_full
    return elevation_adjustment unless elevation_adjustment.present?
    "#{elevation_adjustment} #{elevation_adjustment_unit} #{elevation_adjustment_direction}"
  end

  def windage_adjustment_full
    return windage_adjustment unless windage_adjustment.present?
    "#{windage_adjustment} #{windage_adjustment_unit} #{windage_adjustment_direction}"
  end

  def group_size_full
    return group_size unless group_size.present?
    "#{group_size} #{group_size_unit}"
  end

  def self.next_number(scope, shooting_log = nil, load = nil, distance = nil)
    if ! shooting_log.present? && ! load.present? && ! distance.present?
      return 1
    end
    if shooting_log.present?
      scope = scope.where(shooting_log_id: shooting_log)
    end
    if load.present?
      scope = scope.where(load_id: load)
    end
    if distance.present?
      scope = scope.where(distance: distance)
    end
    numbers = scope.pluck(:number)
    highest_number = numbers.sort.last
    return 1 unless highest_number.present?
    highest_number + 1
  end

  def clone_record
    new_shooting_group = self.dup
    scope = self.class.by_user(user)
    new_shooting_group.number = self.class.next_number(scope, shooting_log.id, load.id, distance)
    new_shooting_group.group_size = nil
    new_shooting_group
  end
end

app/controllers/shooting_groups_controller.rb
# frozen_string_literal: true

class ShootingGroupsController < ApplicationController
  include DiscardController

  before_action :set_index, only: [:index]
  before_action :set_shooting_group, only: [:show, :edit, :update, :discard, :restore, :delete, :destroy, :clone]
  before_action :set_associations, only: [:new, :create, :edit, :update, :clone]
  after_action :verify_authorized, except: [:index, :autocomplete, :next_number]
  after_action :verify_policy_scoped, only: [:index, :next_number]

  # GET /shooting_groups
  # GET /shooting_groups.json
  def index
  end

  # GET /shooting_groups/1
  # GET /shooting_groups/1.json
  def show
    authorize @shooting_group
  end

  # GET /shooting_groups/new
  def new
    @shooting_group = ShootingGroup.new(shooting_group_new_params)
    @shooting_group.user = current_user
    authorize @shooting_group
  end

  # GET /shooting_groups/1/edit
  def edit
    authorize @shooting_group
  end

  # POST /shooting_groups
  # POST /shooting_groups.json
  def create
    @shooting_group = ShootingGroup.new(shooting_group_params)
    @shooting_group.user = current_user
    authorize @shooting_group

    respond_to do |format|
      if @shooting_group.save
        format.html { redirect_to @shooting_group, notice: "Shooting group was successfully created." }
        format.json { render :show, status: :created, location: @shooting_group }
      else
        format.html { render :new }
        format.json { render json: @shooting_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shooting_groups/1
  # PATCH/PUT /shooting_groups/1.json
  def update
    authorize @shooting_group
    respond_to do |format|
      if @shooting_group.update(shooting_group_params)
        format.html { redirect_to @shooting_group, notice: "Shooting group was successfully updated." }
        format.json { render :show, status: :ok, location: @shooting_group }
      else
        format.html { render :edit }
        format.json { render json: @shooting_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shooting_groups/1
  # DELETE /shooting_groups/1.json
  def destroy
    authorize @shooting_group
    @shooting_group.destroy
    respond_to do |format|
      format.html { redirect_to shooting_groups_url, notice: "Shooting group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /shooting_groups/next_number.json
  def next_number
    scope = policy_scope(ShootingGroup).all
    next_number = ShootingGroup.next_number(scope, params[:shooting_log_id], params[:load_id], params[:distance])
    render json: { next_number: next_number }
  end

  # GET /shooting_groups/1/clone
  def clone
    @shooting_group = @shooting_group.clone_record
    authorize @shooting_group
    render :new
  end

  private
    def set_index(joins = :shooting_log)
      super(joins)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_shooting_group
      @shooting_group = policy_scope(ShootingGroup).find(params[:id])
    end

    def set_associations
      @shooting_logs = policy_scope(ShootingLog).kept
      @loads = policy_scope(Load).kept
      @calibers = policy_scope(Caliber).kept
    end

    def shooting_group_new_params
      params.permit(:shooting_log_id, :load_id, :caliber_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shooting_group_params
      params.require(:shooting_group).permit(:shooting_log_id, :load_id, :number,
                                             :distance, :distance_unit, :shots, :caliber_id,
                                             :elevation_adjustment, :elevation_adjustment_direction, :elevation_adjustment_unit,
                                             :windage_adjustment, :windage_adjustment_direction, :windage_adjustment_unit,
                                             :wind_speed, :wind_speed_unit, :wind_direction,
                                             :group_size, :group_size_unit)
    end

    def sortable_columns
      ["shooting_logs.date"]
    end

    def default_sort_column
      "shooting_logs.date"
    end

    def default_sort_direction
      "desc"
    end
end

app/helpers/shooting_groups_helper.rb
# frozen_string_literal: true

module ShootingGroupsHelper
end

app/views/shooting_groups/_form.html.erb
<%= simple_form_for(@shooting_group) do |f| %>
  <%= render 'form_errors', f: f %>

  <div class="form-inputs">
    <%= f.association :shooting_log, label_method: :date, collection: @shooting_logs %>
    <%= f.association :caliber, collection: @calibers %>
    <%= f.input :load_id, collection: @calibers,
                      label_method: :name, as: :grouped_select, group_method: :loads, required: true,
                      input_html: { class: "#{is_invalid(@shooting_group, :load)}" } %>
    <%= f.input :distance do %>
      <%= f.input_field :distance, class: 'form-control input_field col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :distance_unit, as: :select, collection: Unit.distance, class: 'col-sm-2' %>
    <% end %>
    <%= f.input :number %>
    <%= f.input :shots %>
    <%= f.input :elevation_adjustment do %>
      <%= f.input_field :elevation_adjustment, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :elevation_adjustment_unit, as: :select, collection: Unit.scope_adjustment, class: 'col-sm-2' %>
      <%= f.label 'Direction:', class: 'col-sm-2 text-sm-right' %>
      <%= f.input_field :elevation_adjustment_direction, as: :select, collection: ['up','down'], class: 'col-sm-2' %>
    <% end %>
    <%= f.input :windage_adjustment do %>
      <%= f.input_field :windage_adjustment, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :windage_adjustment_unit, as: :select, collection: Unit.scope_adjustment, class: 'col-sm-2' %>
      <%= f.label 'Direction:', class: 'col-sm-2 text-sm-right' %>
      <%= f.input_field :windage_adjustment_direction, as: :select, collection: ['left','right'], class: 'col-sm-2' %>
    <% end %>
    <%= f.input :wind_speed do %>
      <%= f.input_field :wind_speed, class: 'col-sm-3' %>
      <%= f.input_field :wind_direction, class: 'col-sm-4', placeholder: 'Direction in degrees' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :wind_speed_unit, as: :select, collection: Unit.velocity, class: 'col-sm-2' %>
    <% end %>
    <%= f.input :group_size do %>
      <%= f.input_field :group_size, class: 'col-sm-3' %>
      <%= f.label 'Unit:', class: 'col-sm-2 col-lg-1 text-sm-right' %>
      <%= f.input_field :group_size_unit, as: :select, collection: Unit.length, class: 'col-sm-2' %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/shooting_groups/edit.html.erb
<%= edit_header(@shooting_group) %>
<%= render 'form', shooting_group: @shooting_group %>

app/views/shooting_groups/index.html.erb
<%= index_header(ShootingGroup) %>

<%= search_bar(ShootingGroup) %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= sort_link 'shooting_logs.date', 'Name' %></th>
      <th>Load</th>
      <th>Group size</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shooting_groups.each do |shooting_group| %>
      <tr>
        <td><%= link_to shooting_group.name, shooting_group %></td>
        <td><%= shooting_group.load.name %></td>
        <td><%= shooting_group.group_size %></td>
        <td>
          <%= index_actions(shooting_group) do %>
            <%= link_to('Clone', clone_shooting_group_path(shooting_group), class: 'dropdown-item') %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pagination(ShootingGroup) %>

app/views/shooting_groups/new.html.erb
<%= new_header(@shooting_group) %>
<%= render 'form', shooting_group: @shooting_group %>

app/views/shooting_groups/show.html.erb
<%= show_header(@shooting_group) %>

<dl class='dl-horizontal'>
  <dt>Shooting log:</dt>
  <dd><%= link_to @shooting_group.shooting_log.date, @shooting_group.shooting_log %></dd>

  <dt>Caliber:</dt>
  <dd><%= @shooting_group.caliber.name %></dd>

  <dt>Load:</dt>
  <dd><%= link_to @shooting_group.load.name, @shooting_group.load %></dd>

  <dt>Distance:</dt>
  <dd><%= @shooting_group.distance_full %></dd>

  <dt>Number:</dt>
  <dd><%= @shooting_group.number %></dd>

  <dt>Shots:</dt>
  <dd><%= @shooting_group.shots %></dd>

  <dt>Elevation adjustment:</dt>
  <dd><%= @shooting_group.elevation_adjustment_full %></dd>

  <dt>Windage adjustment:</dt>
  <dd><%= @shooting_group.windage_adjustment_full %></dd>

  <dt>Wind speed:</dt>
  <dd><%= @shooting_group.wind_speed_full %></dd>

  <dt>Group size:</dt>
  <dd><%= @shooting_group.group_size_full %></dd>
</dl>