config/routes.rb
Rails.application.routes.draw do
  concern :discard do
    member do
      get 'discard'
      patch 'discard'
      patch 'restore'
      get 'delete', constraints: { format: 'js' }
    end
  end
  concern :autocomplete do
    collection do
      get 'autocomplete'
    end
  end
  concern :clone do
    member do
      get 'clone'
    end
  end
  resources :shooting_velocities do
    concerns [:autocomplete, :discard]
  end
  resources :guns do
    concerns [:discard]
  end
  resources :shooting_groups do
    collection do
      get 'next_number', constraints: { format: 'json' }
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :shooting_logs do
    concerns [:autocomplete, :discard]
  end
  resources :shooting_locations do
    concerns [:discard]
  end
  resources :loads do
    member do
      get 'calculate_velocity'
    end
    concerns [:autocomplete, :discard, :clone]
  end
  resources :brasses do
    concerns [:discard]
  end
  resources :calibers do
    concerns [:discard]
  end
  resources :primers do
    concerns [:discard]
  end
  resources :powders do
    concerns [:discard]
  end
  resources :bullets do
    concerns [:discard]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  get '/ballistic_calculator', to: 'ballistic_calculator#new', as: :ballistic_calculator
  post '/ballistic_calculator', to: 'ballistic_calculator#create', as: nil
  get 'users/settings', to: 'user_settings#show', as: :user_settings
  get 'users/settings/edit', to: 'user_settings#edit', as: :user_settings_edit
  put 'users/settings', to: 'user_settings#update', as: nil
  get "/*id" => 'pages#show', as: :page, format: false
  root to: "pages#show", id: 'home'
end

app/models/ballistic_calculator.rb
# frozen_string_literal: true

# REF: https://www.ar15.com/forums/armory/Bullet_Drop_Formula/42-351773/#i3198632
class BallisticCalculator
  include ActiveModel::Model

  attr_accessor :ballistic_coefficient
  attr_accessor :velocity
  attr_accessor :height_of_sight
  attr_accessor :zero_range

  attr_accessor :ranges_max
  attr_accessor :ranges_interval
  attr_accessor :wind_speed
  attr_accessor :scope_moa_adjustment

  attr_accessor :caliber_id
  attr_accessor :load_id
  attr_accessor :gun_id

  validates :ballistic_coefficient, numericality: true
  validates :velocity, numericality: true
  validates :height_of_sight, numericality: true
  validates :zero_range, numericality: true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
    @ranges_max ||= 500
    @ranges_interval ||= 100
    @wind_speed ||= 0
  end

  [
    :ballistic_coefficient,
    :velocity,
    :height_of_sight,
    :zero_range,
    :scope_moa_adjustment,
  ].each do |a|
    define_method(a) do
      value = instance_variable_get("@#{a}")
      if value.present?
        if value.to_i.to_s == value.to_s || value.to_f.to_s == value.to_s
          value = value.to_f
        end
      end
      value
    end
  end

  def self.ranges(max, interval)
    max = max.to_i
    interval = interval.to_i
    (0..max).step(interval).to_a
  end

  def scope_moa_adjustment_name
    Unit.scope_moa_adjustment_name(scope_moa_adjustment)
  end

  # remaining velocity, fps
  def RV(range)
    ((Math.sqrt(velocity)) - 0.00863 * (range.to_f / ballistic_coefficient))**2
  end

  # dummy variable
  def K
    2.878 / (ballistic_coefficient * Math.sqrt(velocity))
  end

  # time of flight, seconds
  def TF(range)
    (3.0 * range.to_f) / (velocity * (1 - (0.003 * range * self.K)))
  end

  # dummy variable
  def F(range)
    193 * (1 - ((0.37 * (velocity - self.RV(range))) / velocity))
  end

  # total drop from line of departure, inches
  def DR(range)
    self.F(range) * self.TF(range)**2
  end

  # maximum height of trajectory above sight line, inches
  def MH(range)
    (48.6 * self.TF(range)**2) - (0.4 * height_of_sight)
  end

  # elevation required, moa
  def EL(range)
    (100.0 * (self.DR(range) + height_of_sight)) / range.to_f
  end

  # bullet path above or below line of sight, inches
  def BP(range)
    el0 = self.EL(zero_range)
    if range < zero_range
      el1 = 0.0
    else
      el1 = self.EL(range)
    end
    ((el0 - el1) * range.to_f) / 100.0
  end

  # bullet path above or below line of sight, moa
  def BP_moa(range)
    return 0.0 if range == 0
    self.BP(range) / (range.to_f / 100.0)
  end

  def BP_clicks(range)
    return 0 if range == 0
    return 0 unless scope_moa_adjustment.present?
    adjustment_at_range = ((range.to_f / 100.0) * scope_moa_adjustment)
    (self.BP_moa(range) / adjustment_at_range).abs
  end

  # wind deflection, inches
  def WD(range, wa = 180)
    wind_angle = wa.to_f
    # if wind_angle > 180.0
    #  wind_angle = 360.0 - wind_angle
    # end
    (wind_speed.to_f / 10) * (wind_angle) * (self.TF(range) - ((3 * range.to_f) / velocity.to_f))
  end

  # wind deflection, moa
  def WD_moa(range, wind_angle = 180)
    return 0.0 if range == 0
    self.WD(range, wind_angle) / (range.to_f / 100.0)
  end

  # USMC method
  # http://www.millettsights.com/resources/shooting-tips/mathematics-for-precision-shooters/
  def wind_drift_moa(range, single_value = false)
    value = ((range.to_f / 100.0) * wind_speed.to_f) / 15
    return value if single_value
    [value.round(1), self.WD_moa(range).round(1)]
  end

  def wind_drift(range)
    moa = self.wind_drift_moa(range, true)
    value = moa * (range.to_f / 100.0)
    [value.round(1), self.WD(range).round(1)]
  end

  def wind_drift_clicks(range)
    return 0 if range == 0
    return 0 unless scope_moa_adjustment.present?
    adjustment_at_range = ((range.to_f / 100.0) * scope_moa_adjustment)
    moa = self.wind_drift_moa(range)
    min = (moa[0] / adjustment_at_range)
    max = (moa[1] / adjustment_at_range)
    [min.round(0), max.round(0)]
  end
end

app/controllers/ballistic_calculator_controller.rb
# frozen_string_literal: true

class BallisticCalculatorController < ApplicationController
  before_action :set_associations

  respond_to :html, :js

  # GET /ballistic_calculator
  def new
    @ballistic_calculator = BallisticCalculator.new
    authorize @ballistic_calculator
  end

  # POST /ballistic_calculator
  # POST /ballistic_calculator.js
  def create
    @ballistic_calculator = BallisticCalculator.new(ballistic_calculator_params)
    authorize @ballistic_calculator
    @ranges = BallisticCalculator.ranges(@ballistic_calculator.ranges_max, @ballistic_calculator.ranges_interval)

    respond_to do |format|
      if @ballistic_calculator.valid?
        format.js
        format.html { render :show }
      else
        format.js { render :new }
        format.html { render :show }
      end
    end
  end

  private
    def set_associations
      @calibers = policy_scope(Caliber).all
      @loads = policy_scope(Load).all
      @guns = policy_scope(Gun).all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ballistic_calculator_params
      params.require(:ballistic_calculator).permit(:caliber_id, :load_id, :gun_id,
                                                   :ballistic_coefficient, :velocity,
                                                   :height_of_sight, :zero_range,
                                                   :ranges_max, :ranges_interval,
                                                   :scope_moa_adjustment, :wind_speed)
    end
end

app/helpers/ballistic_calculators_helper.rb
# frozen_string_literal: true

module BallisticCalculatorsHelper
end

app/views/ballistic_calculator/_form.html.erb
<%#= new_header(@ballistic_calculator) %>
<%#= render 'form', ballistic_calculator: @ballistic_calculator %>
<%= simple_form_for(@ballistic_calculator, url: ballistic_calculator_path, method: :post, remote: true, html: { data: { modal: true }}) do |f| %>
  <%= render 'form_errors', f: f %>

  <div class="form-inputs">
    <%= f.input :caliber_id, collection: @calibers, required: false %>
    <%= f.input :load_id, collection: @calibers,
                      label_method: :name, as: :grouped_select, group_method: :loads, required: false %>
    <%= f.input :gun_id, collection: @calibers,
                      label_method: :name, as: :grouped_select, group_method: :guns, required: false %>
    <%= f.input :ammo, label: 'Ammunition' do %>
      <%= f.label 'Ballistic Coefficient', required: true, class: 'col-sm-4 text-sm-right' %>
      <%= f.input_field :ballistic_coefficient, required: true, class: 'form-control input_field col-sm-2' %>
      <%= f.label 'Velocity', required: true, class: 'col-sm-3 text-sm-right' %>
      <%= f.input_field :velocity, required: true, class: 'form-control input_field col-sm-2' %>
    <% end %>
    <%= f.input :firearm, label: 'Firearm' do %>
      <%= f.label 'Height of Sight', required: true, class: 'col-sm-4 text-sm-right' %>
      <%= f.input_field :height_of_sight, required: true, class: 'form-control input_field col-sm-2' %>
      <%= f.label 'Zero Range', required: true, class: 'col-sm-3 text-sm-right' %>
      <%= f.input_field :zero_range, required: true, class: 'form-control input_field col-sm-2' %>
    <% end %>
    <%#= f.input :height_of_sight, required: true, wrapper: :horizontal_input_field, input_html: { class: 'input_field col-sm-2' }, wrapper_html: { class: 'offset-sm-3' } %>
    <%#= f.input :zero_range, required: true, wrapper: :horizontal_input_field, input_html: { class: 'input_field col-sm-2' }, wrapper_html: { class: 'offset-sm-3' } %>
    <%= f.input :range do %>
      <%= f.label 'Maximum Range', class: 'col-sm-4 text-sm-right' %>
      <%= f.input_field :ranges_max, class: 'form-control input_field col-sm-2' %>
      <%= f.label 'Interval', class: 'col-sm-3 text-sm-right' %>
      <%= f.input_field :ranges_interval, class: 'form-control input_field col-sm-2' %>
    <% end %>
    <%= f.input :advanced do %>
      <%= f.label 'Scope MOA Adjustment', class: 'col-sm-4 text-sm-right' %>
      <%= f.input_field :scope_moa_adjustment, as: :select, collection: Unit.scope_moa_adjustments, class: 'col-sm-2' %>
      <%= f.label 'Wind Speed', class: 'col-sm-3 text-sm-right' %>
      <%= f.input_field :wind_speed, class: 'col-sm-2' %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/ballistic_calculator/_show.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Ballistic Calculator Results</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body">
      <table class='table'>
        <tr>
          <td class="table-dark">Ballistic coefficient:</td>
          <td class="table-secondary"><%= @ballistic_calculator.ballistic_coefficient %></td>
          <td class="table-dark">Velocity:</td>
          <td class="table-secondary"><%= @ballistic_calculator.velocity %></td>
        </tr>
        <tr>
          <td class="table-dark">Height of sight:</td>
          <td class="table-secondary"><%= @ballistic_calculator.height_of_sight %></td>
          <td class="table-dark">Zero range:</td>
          <td class="table-secondary"><%= @ballistic_calculator.zero_range %></td>
        </tr>
        <tr>
          <td class="table-dark">Scope MOA Adjustment:</td>
          <td class="table-secondary"><%= @ballistic_calculator.scope_moa_adjustment_name %></td>
          <td class="table-dark">Wind speed:</td>
          <td class="table-secondary"><%= @ballistic_calculator.wind_speed %></td>
        </tr>
      </table>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Range</th>
            <th>Drop (in)</th>
            <th>Drop (MOA)</th>
            <th>Drop (clicks)</th>
            <th>Wind Drift (in)<a class="questionmark-popover" tabindex="0" role="button" data-toggle="popover" data-content="Uses USMC formula for estimation" ><span class="fa fa-question-circle"></span></a></th>
            <th>Wind Drift (MOA)<span class="fa fa-question-circle" data-toggle="tooltip" title="Uses USMC formula for estimation"></span></th>
            <th>Wind Drift (clicks)</th>
          </tr>
          <% @ranges.each do |range| %>
            <tr>
              <td><%= range %></td>
              <td><%= @ballistic_calculator.BP(range).round(2) %></td>
              <td><%= @ballistic_calculator.BP_moa(range).round(1) %></td>
              <td><%= @ballistic_calculator.BP_clicks(range).round(0) %></td>
              <td><%= @ballistic_calculator.wind_drift(range)[0] %></td>
              <td><%= @ballistic_calculator.wind_drift_moa(range)[0] %></td>
              <td><%= @ballistic_calculator.wind_drift_clicks(range)[0] %></td>
            </tr>
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/ballistic_calculator/create.js.erb
$('[role="main"]').html("<%= escape_javascript(render 'ballistic_calculator/form') %>")
$('#mainModal').html("<%= escape_javascript(render 'ballistic_calculator/show') %>");
$('#mainModal').modal('show');

app/views/ballistic_calculator/new.html.erb
<%= render 'form' %>

app/views/ballistic_calculator/new.js.erb
$('[role="main"]').html("<%= escape_javascript(render 'ballistic_calculator/form') %>")

app/views/ballistic_calculator/show.html.erb
<dl class='dl-horizontal'>
  <dt>Ballistic coefficient:</dt>
  <dd><%= @ballistic_calculator.ballistic_coefficient %></dd>

  <dt>Velocity:</dt>
  <dd><%= @ballistic_calculator.velocity %></dd>

  <dt>Height of sight:</dt>
  <dd><%= @ballistic_calculator.height_of_sight %></dd>

  <dt>Zero range:</dt>
  <dd><%= @ballistic_calculator.zero_range %></dd>

</dl>